### ISSUE TITLE
Java 11 build not available due to gradle version being so old

### ISSUE THREAD

**Issue by jodygarnett** [mapfish/mapfish-print-v2#11]
GeoTools now requires Java 11, and as part [OpenGIS Harmonization](https://www.osgeo.org/opengis-harmonization/) we need to change some package names in GeoTools requiring a new release of mapfish-print-v2  for downstream projects GeoServer and GeoNode.

* Presently: gradle version 3, works with Java 8 (not Java 11) and uses plugins jetty and maven 

* Minimim: gradle version 5, works with Java 11, requires upgrade to plugins getty and maven-plublish

Does camptocamp have any developers who are comfortable supplying this project with a modern gradle environment?

**Comment by jodygarnett** [comment]
@cmangeat it looks like you have worked on build.gradle here in the past; is this something you are comfortable upgrading?

There is some budget for this activity via OSGeo, goal is to have something ready for Bolsean code sprint (or drop the functionality from downstream projects).

See also https://github.com/GeoNode/geonode/issues/11208

**Comment by jodygarnett** [comment]
Researching more - GeoNode developers (GeoSolutions consultants in the case) also have a fork of mapfish-print-v2 with some new capabilities, and a maven build system.

https://github.com/geosolutions-it/mapfish-print

Ideally we can reduce duplication and testing overhead during Bolsena sprint.

**Comment by jodygarnett** [comment]
Looking into this as its oddly be ideal to fix the build system prior to the code sprint (as it is a distinct activity that does not require any changes to the upstream geotools library). Upgrading to geotools 29.2 would be fine to test Java 11 build change.

The https://github.com/geosolutions-it/mapfish-print fork already has a maven pom.xml file defined. Is this sufficient or is it project policy to use gradle?

**Comment by sebr72** [comment]
As discussed, please update the code as required.
